### ISSUE TITLE
Compiling on MSVC and jemalloc

### ISSUE THREAD

**Issue by QuantumEntangledAndy** [bytebeamio/rumqtt#161]
Jemalloc will does not support [msvc](https://github.com/gnzlbg/jemallocator/issues/91). Can we add jamalloc behind an option like this:

```rust
#[cfg(not(target_env = "msvc"))]
#[global_allocator]
static ALLOC: jemallocator::Jemalloc = jemallocator::Jemalloc;
```

With this for the Cargo.toml
```toml
[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = "0.3.2"
```

so that it will not be required on such builds
