### ISSUE TITLE
rustfmt

### ISSUE THREAD

**Issue by prataprc** [bytebeamio/rumqtt#403]
```toml
max_width = 90
array_width = 80
attr_fn_like_width = 80
chain_width = 80
fn_call_width = 80
single_line_if_else_max_width = 80
struct_lit_width = 50
```

The broad idea is to decrease the `max_width` from 100 (rustfmt-default) to 90 and increase all the other widths. With 90-char width it is easy to do split-window in monitors 24inch and above. Code review, diff-tools (like `vimdiff`) looks/feels much better.

By increasing the width of other parameters like `chain_width`, `fn_call_width`, .. the code can get much denser horizontally.

Please change or add to the configurations listed above.

All this varies from person-to-person. In any case, I highly recommend to add rustfmt.toml in the root directory of `rumqtt` repository. That way, developers can choose to have different formatting for different repositories, but single formatting is enforced on `rumqtt`.
