### ISSUE TITLE
rumqttd: disconnect notification does not fire for non-graceful disconnects.

### ISSUE THREAD

**Issue by nathansizemore** [bytebeamio/rumqtt#775]
# Expected Behavior

When the OS reports a socket is disconnected, the link/broker would report the notification.

# Current Behavior

No event is published signaling the disconnect.

## Context

```toml
id = 0

[router]
id = 0
max_connections = 10010
max_outgoing_packet_count = 200
max_segment_size = 104857600
max_segment_count = 10

[v4.1]
name = "v4-1"
listen = "0.0.0.0:1337"
next_connection_delay_ms = 1
    [v4.1.connections]
    connection_timeout_ms = 60000
    max_payload_size = 20480
    max_inflight_count = 100
    dynamic_filters = true
```

```rust
let mut config = load_cfg();
if let Some(ref mut v4) = config.v4 {
    if let Some(settings) = v4.get_mut("1") {
        settings.connections.external_auth = Some(Arc::new(authorize_client));
    }
}

let mut broker = Broker::new(config);
let (mut link_tx, mut link_rx) = broker.link("singlenode").unwrap();
thread::spawn(move || {
    broker.start().unwrap();
});

link_tx.subscribe("#").unwrap();

loop {
    let notification = match link_rx.recv().unwrap() {
        Some(v) => v,
        None => continue,
    };

    match notification {
        Notification::Forward(forward) => {
            println!(
                "Topic = {:?}, Payload = {} bytes",
                forward.publish.topic,
                forward.publish.payload.len()
            );
        }
        Notification::Disconnect(d, props) => {
            println!("========== disconnect: \n{d:#?}\n{props:#?}");
        }
        v => {
            println!("{v:?}");
        }
    }
}
```

Connect client. Remove internet capabilities from client. Eventually, when the OS reports the socket as disconnected, tracing picks up, but no notification for the disconnect is sent. Only this in logs: 

> ERROR rumqttd::server::broker: Disconnected!!, error: Network(Io(Os { code: 110, kind: TimedOut, message: "Connection timed out" }))

To shorten the default OS timeout to 1sec with 3 attempts, I pulled in libc to test with this:

```rust
let (stream, addr) = match listener.accept().await {
    Ok((s, r)) => {
        let fd = s.as_raw_fd();
        let optval: i32 = 1;
        let optlen = mem::size_of::<i32>() as libc::socklen_t;
        let _ = unsafe {
            libc::setsockopt(
                fd,
                libc::SOL_SOCKET,
                libc::SO_KEEPALIVE,
                &1 as *const _ as *const libc::c_void,
                optlen,
            )
        };
        let _ = unsafe {
            libc::setsockopt(
                fd,
                libc::IPPROTO_TCP,
                libc::TCP_KEEPIDLE,
                &1 as *const _ as *const libc::c_void,
                optlen,
            )
        };
        let _ = unsafe {
            libc::setsockopt(
                fd,
                libc::IPPROTO_TCP,
                libc::TCP_KEEPCNT,
                &3 as *const _ as *const libc::c_void,
                optlen,
            )
        };
        let _ = unsafe {
            libc::setsockopt(
                fd,
                libc::IPPROTO_TCP,
                libc::TCP_KEEPINTVL,
                &1 as *const _ as *const libc::c_void,
                optlen,
            )
        };

        (s, r)
    }
    Err(e) => {
        error!(error=?e, "Unable to accept socket.");
        continue;
    }
};
```

* Operating System: Linux
* Toolchain version:  rustc 1.74.1 (a28077b28 2023-12-04)
